spring :
    datasource :

        # PostgreSQL
        url :      jdbc:postgresql://localhost:5432/services
        #

        # MySQL
#        url :      jdbc:mysql://localhost:3306/services
        #

        username : postgres
        password : root
    jpa :
        hibernate :
            ddl-auto : update
        show-sql : true

        # PostgreSQL
        properties :
            hibernate :
                dialect : org.hibernate.dialect.PostgreSQLDialect
                jdbc :
                    lob :
                        non_contextual_creation : true
        #

server :
    port : 8080
    ssl:
        enabled : true
        key-store-type : PKCS12
        key-store :          classpath:ssl/server.pfx
        key-store-password : root
